spring:
  application:
    name: sing-spring-cloud-eureka-client4
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      


  logging:
    level:
      org.springframework.web: DEBUG
      com.singplayground.eureka.client4.controller: DEBUG